console.log("[*] JavaScript console started")
console.log("[*] starting ePod service")
console.log("[*] Connecting to 177.30.15.122")
console.log("waiting for server acess")
console.log("downloading required packages")
console.log("0,11KB/12.000MB")
console.log("0,20KB/12.000MB")
console.log("0,500MB/12.000MB")
console.log("12.000MB/12.000MB")
console.log("...")
console.log("[*] now importing com.drawdrimer.epod.wab")
console.log("installing package")
console.log("updating WAB list")
console.log("insert ePod IP and port:")
